name: NodeJS with Webpack

on: [ workflow_dispatch ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v4
    - run: echo ${{github.ref}}
    
